apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zuul-proxy
spec:
  replicas: 2
  selector:                                                                                                                   
    matchLabels:                                                                                                              
      app: zuul-proxy
  template:
    metadata:
      labels:
        app: zuul-proxy
    spec:
      containers:
      - name: zuul-proxy
        image: harbor.k8s.maimaiti.site/mydemo2/zuul-proxy:<BUILD_TAG>
        ports:
        - containerPort: 8801
        resources:
          requests:
            memory: 512Mi
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8101
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8101
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka
              key: eureka_server_address
        - name: JVM_OPTS
          value: "-Xms512m -Xmx512m" 

---

apiVersion: v1
kind: Service
metadata:
  name: zuul-proxy
spec:
  selector:
    app: zuul-proxy
  ports:
  - protocol: TCP
    port: 8801
    targetPort: 8801

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zuul-proxy
spec:
  rules:
  - host: zuul-proxy.k8s.maimaiti.site
    http:
      paths:
      - backend:
          serviceName: zuul-proxy
          servicePort: 8801
        path: /
      
      
