server:
  port: 8201
spring:
  application:
    name: user-service
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipaddress}:${spring.application.name}:${server.port}
    hostname: ${spring.cloud.client.ipaddress}
  