apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 2
  selector:                                                                                                                   
    matchLabels:                                                                                                              
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: harbor.k8s.maimaiti.site/mydemo2/user-service:<BUILD_TAG>
        ports:
        - containerPort: 8201
        resources:
          requests:
            memory: 512Mi
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8201
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8201
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   timeoutSeconds: 5
        env:
        - name: EUREKA_SERVER_ADDRESS
          valueFrom:
            configMapKeyRef:
              name: eureka
              key: eureka_server_address
        - name: JVM_OPTS
          value: "-Xms512m -Xmx512m"       
      
